- name: изтегли най-новия код
  become: yes
  git:
    repo: "{{repo_url}}"
    dest: '{{root}}'
    version: "{{repo_version}}"
    key_file: "{{repo_key_file}}"
    accept_hostkey: yes
    force: yes
  register: code
  tags: push

  #- name: Restart horodeya
  #  debug:
  #    msg: Restart horodeya
  #  notify: restart horodeya
  #  changed_when: True
  #  tags: restart

- name: fix permissions 0
  become: yes
  file:
    path: '{{root}}'
    state: directory
    owner: horodeya
    group: www-data
    mode: u=rwx,g=rwx,o=r
    recurse: yes

- name: fix permissions 2
  become: yes
  file:
    path: '{{root}}/.git'
    state: directory
    owner: '{{admin_user}}'
    group: '{{admin_user}}'
    recurse: yes

- name: generate manage.sh
  become: yes
  template:
    src: 'files/manage.sh'
    dest: '{{root}}/manage.sh'
    owner: horodeya
    group: www-data

- name: install python dependencies
  become: yes
  pip:
    requirements: '{{root}}/requirements.txt'
    virtualenv: '{{root}}/venv'
    virtualenv_python: python3
  tags: install

- name: apply migrations to database
  shell: '{{root}}/manage.sh migrate'
  args:
    chdir: '{{root}}'
  tags:
    migrate

- name: make translations
  shell: '{{root}}/manage.sh compilemessages -l bg'
  args:
    chdir: '{{root}}'
  tags: translate

- name: arrange static files
  shell: '{{root}}/manage.sh collectstatic --noinput'
  args:
    chdir: '{{root}}'
  tags: static

- name: restart
  become: yes
  file: 
    path: /etc/uwsgi-emperor/vassals/horodeya.ini
    state: touch
  tags: restart

- name: schedule hourly backups
  cron:
    name: 'Hourly backups'
    special_time: hourly
    job: '/opt/horodeya/backup.sh'
